hw 16 DB-App
vikkanaev/thinknetica_golang_core pull request #13
Opened 2022-06-04 11:42 UTC by vikkanaev

В рамках задания по работе с базой:
- Разработан пакет storage, содержащий интерфейс и структуру фильм
- Добавление фильмов сделано транзакцией по принципу все или ничего
- Удаление фильма сделано транзакцией что бы очистить связанные таблицы
- В интерфейс пакета storage добавлен метод Close() для аккуратного завершения работы с базой

2022-06-05 07:04 UTC, DmitriyVTitov requested changes
Не принято.

2022-06-05 07:04 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +func New(ctx context.Context) *PG {
желательно делать функцию гибче: я могу не иметь пароля в переменной окружения и тогда я захочу передать полную строку
это нарушение OCP в общем-то

2022-06-05 07:04 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +		log.Fatalf("Unable to connect to database: %v\n", err)
log.Fatal в вызываемой функции недопустим!
из-за этого не могу принять, много раз об этом говорил

2022-06-05 08:39 UTC, vikkanaev commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +func New(ctx context.Context) *PG {
Исправил. Перенес в функцию main() пакета main

2022-06-05 08:40 UTC, vikkanaev commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +		log.Fatalf("Unable to connect to database: %v\n", err)
Согласен. Один упустил при копипасте. Исправил!

2022-06-06 14:12 UTC, DmitriyVTitov approved these changes
ОК, но есть пара замечаний.

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/cmd/main.go
> +}
Контекст нельзя хранить в состоянии! Это прямо таки противоречит его сути.
Контекст сопровождает один запрос и может содержать как сопутствующие данные (X-Request-ID, к примеру), так и таймаут для этого запроса. Контекст не может быть общим для всей службы.

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +}
здесь то же самое
если нужна краткость и не писать `context.Background()` - то следует объявить глобальную переменную в пакете

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +	}
в случае ошибки нужно возвращать nil как значение по умолчанию для указателя

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +	}
ОК, но можно элегантней:
`WHERE studio_id = $1 OR $1 = 0`

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +	return tx.Commit(pg.ctx)
в рабочем коде таких очевидных комментариев следует избегать

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +	return tx.Commit(pg.ctx)
здесь - ОК

2022-06-06 14:12 UTC, DmitriyVTitov commented on Lesson_16-DB-App/pkg/storage/postgres/postgres.go
> +	batch.Queue(`DELETE FROM films WHERE id = $1`, id)
лучше было в схеме использовать директиву `ON DELETE CASCADE`

2022-06-08 18:52 UTC, merged