Финальный проект
vikkanaev/thinknetica_golang_core pull request #17
Opened 2022-06-11 15:16 UTC by vikkanaev

- Shortener переведен на Mongo

2022-06-13 08:27 UTC, DmitriyVTitov requested changes
Структура микросервиса GW требует переработки. В остальном - всё здорово!

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +}
Не понимаю идеи. Конфигурация - обычно глобальный объект для приложения. Тут же это часть пакета RPC.
Выглядит нелогично.
Вообще имя RPC тут неожиданно, как и название пакета. Да, http-вызовы тоже являются вариантом RPC, но обычно всё же так не называются. Вспоминая комментарий к PR, могу сказать, что gRPC тут не "просится". Его преимущество в более эффективной сериализации данных по сравнению с JSON, что для одной ссылки несущественно. В остальном gRPC использует HTTP/2 в качестве транспорта.
Я бы переделал пакет, в первую очередь изменив название. Сейчас сложно понять для чего этот пакет нужен (см. "Кричащая архитектура").

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +type RPC struct {
Экспортируемый объект должен быть снабжён комментарием. Сейчас его назначение не очень понятно.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/cache.go
> +type Cache struct {
Экспортируемый объект должен быть снабжён комментарием. Сейчас его назначение не очень понятно.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/cache.go
> +type Cache struct {
И вообще: судя по составу полей, это явно не кэш.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/shortner.go
> +type Shortner struct {
Экспортируемый объект должен быть снабжён комментарием. Сейчас его назначение не очень понятно.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +package rpc
Насколько я понимаю, это пакет для взаимодействия с другими микросервисами. Следует разделить его на два - по одному для каждого микросервиса и назвать эти пакеты соответственно. См. принцип SRP.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/shortner.go
> +}
Не очень понятен смысл этого метода. Этих пар может быть очень много, да и вообще: зачем они все вместе? Что с ними делать? Почему возвращаются просто строкой?

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/api/urls.go
> +	url, _ := api.rpc.CachedUrl(key)
не правильный подход: ошибку надо обрабатывать!
если она не пустая - запросить данные в базе

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +}
я бы рекомендовал вынести работу с конфигурацией в отдельный пакет с описанием структуры конфигурации и методов для работы с ней (чтения из файла, например)

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +	return string(body), nil
вообще при работе с сетью стандартным является тип `[]byte`, а не `string`

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/api/urls.go
> +	http.Redirect(w, r, url, http.StatusSeeOther)
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/302
Не уверен на все 100%, но код 303 тут выглядит неверно.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/2-Shortener/cmd/main.go
> +	}
Поскольку у сервиса аналитики нет БД, то пришлось поступить так? ОК.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/2-Shortener/cmd/main.go
> +package main
Исполняемый пакет должен быть в своём подкаталоге.
`/cmd/shortener/main.go`

Вполне возможно, что исполняемых пакетов будет больше одного.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/2-Shortener/cmd/main.go
> +package main
К коду этого микросервиса у меня претензий нет!

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/3-Cache/cmd/main.go
> +package main
Тут тоже всё ОК.

2022-06-13 08:27 UTC, DmitriyVTitov commented on Lesson_20-final-project/4-Analytics/cmd/main.go
> +package main
И тут всё ОК.

2022-06-13 09:09 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/api/urls.go
> +	http.Redirect(w, r, url, http.StatusSeeOther)
исправил

2022-06-13 10:22 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/shortner.go
> +}
удалил

2022-06-13 10:22 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +package rpc
Переделал.

2022-06-13 10:22 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/shortner.go
> +type Shortner struct {
Добавил

2022-06-13 10:23 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/cache.go
> +type Cache struct {
Это описание эндпоинтов сервиса 3-Cache. Добавил комментарии #

2022-06-13 10:23 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +}
Переделал

2022-06-13 10:23 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +type RPC struct {
Добавил описания

2022-06-13 10:24 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +}
Убрал yaml-конфиг. Все настройки передаю через ENV

2022-06-13 10:25 UTC, vikkanaev commented on Lesson_20-final-project/2-Shortener/cmd/main.go
> +	}
Да. Все так

2022-06-13 10:30 UTC, vikkanaev commented on Lesson_20-final-project/2-Shortener/cmd/main.go
> +package main
переделал тут и для всех остальных сервисов

2022-06-13 10:40 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/rpc/rpc.go
> +	return string(body), nil
Исправил

2022-06-13 19:41 UTC, vikkanaev commented on Lesson_20-final-project/1-Gateway/pkg/api/urls.go
> +	url, _ := api.rpc.CachedUrl(key)
Исправил

2022-06-15 08:58 UTC, DmitriyVTitov approved these changes
Мне нравится!

2022-06-15 08:58 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/api/api.go
> +}
так гораздо понятней

2022-06-15 08:58 UTC, DmitriyVTitov commented on Lesson_20-final-project/1-Gateway/pkg/shortner/shortner.go
> +}
я бы вынес это всё просто в константы, но ОК

2022-06-16 18:54 UTC, merged