hw5
vikkanaev/thinknetica_golang_core pull request #4
Opened 2022-04-16 07:06 UTC by vikkanaev

Что сделано:
- Добавлен механизм сохранения результатов сканирования сайтов на диск с использованием io.Writer
- Добавлен механизм чтения ранее сохраненных результатов сканирования сайтов с диск с использованием io.Reader
- При успешном чтении данных с диска новое сканирование сайтов не производится

2022-04-17 19:40 UTC, DmitriyVTitov requested changes
Функции должны возвращать ошибки, а не завершать систему.
log.Fatal() не допустим!

2022-04-17 19:40 UTC, DmitriyVTitov commented on Lesson_5-io/cmd/gosearh.go
> +}
не очень информативно
обычно код используется не так: для получения кода ошибки я должен выполнить приведение типа `error` к типу `notFoundError` и получить код ошибки
```
if e, ok := err.(notFoundErr); ok {
  println(e.code)
}
```

2022-04-17 19:40 UTC, DmitriyVTitov commented on Lesson_5-io/pkg/storage/storage.go
> +		log.Fatal(err)
много раз говорил об этом: так делать нельзя!
не должен пакет завершать работу системы. ошибку надо просто вернуть!

2022-04-17 19:40 UTC, DmitriyVTitov commented on Lesson_5-io/pkg/storage/storage.go
> +	}
после log.Fatal() никакого return уже не будет

2022-04-18 07:27 UTC, vikkanaev commented on Lesson_5-io/pkg/storage/storage.go
> +		log.Fatal(err)
да, вы и правда об этом говорили.
что не отменят факта плохого нейминга нейминг. как из слова log понять что выполнение завершается?

2022-04-18 07:33 UTC, vikkanaev commented on Lesson_5-io/pkg/storage/storage.go
> +		log.Fatal(err)
Чтож, вот и я наступил на эти грабли. Спасибо что обращаете внимание

2022-04-18 11:53 UTC, vikkanaev commented on Lesson_5-io/cmd/gosearh.go
> +}
Исправлено

2022-04-18 11:53 UTC, vikkanaev commented on Lesson_5-io/pkg/storage/storage.go
> +		log.Fatal(err)
Исправлено

2022-04-18 11:53 UTC, vikkanaev commented on Lesson_5-io/pkg/storage/storage.go
> +	}
исправлено

2022-04-18 14:46 UTC, DmitriyVTitov approved these changes
ОК.
Кстати, массив нигде явно не сортируется перед бинарным поиском. Когда-нибудь в процессе эксплуатации это скажется.

2022-04-18 14:46 UTC, DmitriyVTitov commented on Lesson_5-io/cmd/gosearh.go
> +}
не вижу, всё также метод выводит код ошибки
а текстового сообщения нет

2022-04-18 14:46 UTC, DmitriyVTitov commented on Lesson_5-io/cmd/gosearh.go
> +	}
вот это гораздо лучше, печать стека вызовов там явно ни к чему

2022-04-18 14:46 UTC, DmitriyVTitov commented on Lesson_5-io/cmd/gosearh.go
> +	}
лучше избавляться от else
трудно считывать логику

2022-04-18 14:46 UTC, DmitriyVTitov commented on Lesson_5-io/pkg/storage/storage.go
> +	}
в случае ошибки принято возвращать значение по умолчанию, т.е.
```
if err != nil {
  return nil (по умолчанию для слайса), err
}
```

2022-04-18 14:46 UTC, DmitriyVTitov commented on Lesson_5-io/cmd/gosearh.go
> +		return
надо избегать голых `return`

2022-04-18 14:46 UTC, DmitriyVTitov commented on Lesson_5-io/cmd/gosearh.go
> +		return
функция должна заниматься чем-то одним
сканировать, индексировать, записывать в файл - это всё задачи разных функций

2022-04-18 16:10 UTC, vikkanaev commented on Lesson_5-io/pkg/storage/storage.go
> +	}
поправил

2022-04-18 16:11 UTC, vikkanaev commented on Lesson_5-io/cmd/gosearh.go
> +		return
поправил

2022-04-18 16:14 UTC, vikkanaev commented on Lesson_5-io/cmd/gosearh.go
> +}
В прошлый раз исправил на приведение типа. Теперь исправляю и вывод текста ошибки

2022-04-22 07:59 UTC, merged